## 实现2s后在浏览器中显示出hhhh
(1)
function getData() {
    setTimeout(function () {
        return 'hhhhhh'
    }, 2000)
}
app.use((ctx => {
    ctx.body = getData()
}))
因为一调用getData()，就会直接将该函数赋值给ctx.body，因为还没将定时器内内容返回就已经输出了
(2)
async和await必须配对，await必须使用在async函数中，async+await是将异步操作变成同步
app.use( async (ctx => {
    ctx.body = await getData()————————————>调用一个异步的函数，但是等拿到数据后再输出
}))
但是这样还是什么都打印不出来，因为getData函数没返回值
(3)
function getData() {
    let str = ''
    setTimeout(function () {
        str = 'hhhhhh'
    }, 2000)
    return str;
}
app.use( async (ctx => {
    ctx.body = await getData()
}))
和（1）没区别
(4)成功的方法
如果将一个函数return出一个Promise对象(是一个类，使用的时候需要new一下)，这个函数就是异步的，可以使用await，如果这个函数没有使用Promise而是返回了其他的东西，await回来的永远是它直接返回的数据，希望有异步的操纵必须放在Promise中：
function getData(){
    return new Promise(function(resolve,reject){
          setTimeout(function(resolve,reject){
                resolve('hhhhh)
          },2000)
    })
}
app.use( async (ctx => {
    ctx.body = await getData()
}))

# Promise对象延伸
（1）Promise是一个类，使用的时候需要new一下
let promise = new Promise()//创建实例对象
promise.then().then().catch()——————>可以一直点的原因是then()和catch()返回的都是一个promise对象
逻辑错误进入then()方法，程序错误进入catch()方法
（2）
//不加await时的使用:要的是Promise对象就不加await
let res = new Promise(function(resolve,reject){
    $post('xxx/yyy).then(res=>{——————————(then方法返回的就是Promise对象)
        if(res == 'success'){
            resolve('成功')
        }else{
            reject('失败')
        }
    })
})
res.then().then().catch()——————但是在请求里面已经then()完了，不需要再这么使用了
//加await时的使用:要的是数据就加await
let res = await new Promise(function(resolve,reject){——————————等你操作完事了再将结果返回给我
    $post('xxx/yyy).then(res=>{
        if(res == 'success'){
            resolve('成功')
        }else{
            reject('失败')
        }
    })
})
加了await之后res拿到的就是resolve或者reject内部的东西
